css-canvas-medical - James Ding
jamessding/c0522-code-solutions pull request #21
Opened 2022-05-15 01:26 UTC by jamessding

<img width="1713" alt="Screen Shot 2022-05-14 at 5 53 47 PM" src="https://user-images.githubusercontent.com/103629526/168453413-a6703043-6815-4f7b-b239-806fa571a720.png">
<img width="1715" alt="Screen Shot 2022-05-14 at 5 54 11 PM" src="https://user-images.githubusercontent.com/103629526/168453414-4d86084e-c813-4ed3-a59c-72189c48a134.png">
<img width="1719" alt="Screen Shot 2022-05-14 at 5 54 42 PM" src="https://user-images.githubusercontent.com/103629526/168453415-391948ca-ec60-4c76-8d2b-009ff2300d76.png">

2022-05-15 19:56 UTC, codingcodymiller requested changes
Hey James, it looks like your button in the "Ready to learn more?" section is misaligned, please revise and submit a new screenshot with your revision.

2022-05-16 05:41 UTC, jamessding commented
<img width="1719" alt="Screen Shot 2022-05-14 at 5 54 42 PM" src="https://user-images.githubusercontent.com/103629526/168526553-93085aa5-1670-4fe1-857a-39c1ed5c50b9.png">

2022-05-16 16:00 UTC, codingcodymiller requested changes
That button is meant to be centered vertically in that section, but it looks like yours is still resting towards the top of the section

2022-05-20 21:51 UTC, codingcodymiller requested changes

2022-05-20 21:51 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      </div>
Uh oh, this is bad news. You should never use empty columns to create space. Instead, you can make the previous element `column-two-thirds` or make use of a utility class with `justify-content` to control where the items in this row are aligned.

2022-05-20 21:51 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      </div>
Same problem here.

2022-05-23 16:00 UTC, codingcodymiller approved these changes
Nice work on this across the board, good revisions!!

2022-05-23 18:05 UTC, merged

2022-05-28 00:39 UTC, jamessding commented
<img width="1726" alt="Screen Shot 2022-05-27 at 5 31 46 PM" src="https://user-images.githubusercontent.com/103629526/170802870-f7a1168b-9f15-44a8-b16b-3a7f700e8d58.png">
<img width="1724" alt="Screen Shot 2022-05-27 at 5 32 27 PM" src="https://user-images.githubusercontent.com/103629526/170802874-917ed240-eea0-4809-83ef-d601198772c2.png">
<img width="1723" alt="Screen Shot 2022-05-27 at 5 32 40 PM" src="https://user-images.githubusercontent.com/103629526/170802876-a44eafe2-deec-47be-8b8d-eea44820bd12.png">
<img width="1713" alt="Screen Shot 2022-05-27 at 5 32 52 PM" src="https://user-images.githubusercontent.com/103629526/170802877-606efff7-fa03-43c0-bfcf-9abdbce7f281.png">
<img width="1720" alt="Screen Shot 2022-05-27 at 5 32 58 PM" src="https://user-images.githubusercontent.com/103629526/170802879-581c3b37-2f91-4a1c-a727-d9bf93434f53.png">