node-notes-cli - James Ding
jamessding/c0522-code-solutions pull request #83
Opened 2022-06-30 23:23 UTC by jamessding

![Screen Shot 2022-06-30 at 4 20 51 PM](https://user-images.githubusercontent.com/103629526/176794382-8433a80e-d8de-41d1-97a0-f78ef9795d86.png)

2022-06-30 23:38 UTC, thebearingedge requested changes

2022-06-30 23:38 UTC, thebearingedge commented on node-notes-cli/app.js
> +  }
Try to rework this to not use a for ... in loop.

2022-06-30 23:55 UTC, jamessding commented
![Screen Shot 2022-06-30 at 4 53 21 PM](https://user-images.githubusercontent.com/103629526/176797070-9f671512-3bb1-419a-9e94-52466b05977b.png)

2022-07-01 00:23 UTC, thebearingedge approved these changes

2022-07-01 00:25 UTC, merged